import { forwardRef } from "react"
import { Box, Text } from "@chakra-ui/react"
import WaveformChart from "./audio"
import SegmentPieChart from "./SegmentPieChart"

interface AudioReportProps {
  audioData: {
    id: string
    date: string
    time: string
    audioUrl: string
    tags: { name: string; count: number }[]
  }
}

const AudioReportPDF = forwardRef<HTMLDivElement, AudioReportProps>(({ audioData }, ref) => {
  return (
    <Box ref={ref} p={5} borderWidth={1} borderRadius="md">
      <Text fontSize="lg" fontWeight="bold" mb={2}>
        Audio Report
      </Text>

      <Text><strong>Hari & Tanggal:</strong> {audioData.date}</Text>
      <Text><strong>Waktu Rekaman:</strong> {audioData.time}</Text>

      <Text fontSize="md" fontWeight="bold" mt={4}>Waveform & Spectrogram:</Text>
      <WaveformChart 
        mp3File={audioData.audioUrl} 
        audioRef={{ current: null }} 
        showSpectrogram={true} 
      />

      <Text fontSize="md" fontWeight="bold" mt={4}>Tagging Data:</Text>
      {audioData.tags.map((tag, index) => (
        <Text key={index}>🔹 {tag.name}: {tag.count}</Text>
      ))}

      <Text fontSize="md" fontWeight="bold" mt={4}>Tagging Distribution:</Text>
      <SegmentPieChart audioId={audioData.id} />

      <Text fontSize="sm" mt={4} textAlign="center">
        Generated by Bioacoustics Dashboard
      </Text>
    </Box>
  )
})

export default AudioReportPDF
